app/spandex/__init__.py
from flask import Blueprint

spandex = Blueprint('spandex', __name__, template_folder='./templates')

from . import views, errors, models
from .models import Permission


@spandex.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/spandex/views.py
from flask import render_template, redirect, url_for, abort, flash, request,\
    current_app, jsonify
from flask.ext.login import login_required, current_user
from . import spandex
from .forms import EditProfileForm, EditProfileAdminForm, ProjectPostForm, ProjectEditForm, BookingForm, BookingFormAdmin, PublicationPostForm, PublicationEditForm
from .. import db
from .models import Permission, Role, User, Project, Publication, Booking, coauthors
from ..decorators import admin_required
import re
from jinja2 import evalcontextfilter, Markup, escape
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
import csv
import twitter



def anon_view(model):
    # For anon users, show only active objects
    if current_user.is_authenticated():
        if model == Publication:
            objects = model.query.order_by(model.title.asc(), model.year_published.desc(), model.active.desc()).all()
        else:
            objects = model.query.order_by(model.active.desc()).all()
    else:
        if model == Publication:
            objects = model.query.order_by(model.title.asc(), model.year_published.desc()).filter_by(active=True).all()
        else:
            objects = model.query.filter_by(active=True).all()



    return objects

def nav_init():
    # List all navigation items
    nav = { 'researchers' : '', 'projects' : '', 'publications' : ''}
    nav['researchers'] = User.query.order_by(User.name.asc()).all()
    nav['projects'] = anon_view(Project)
    nav['publications'] = anon_view(Publication)

    return nav

@spandex.route('/')
def index():
    api = twitter.Api(consumer_key='4G7C729hkGfcpHDI8zCTFZkBA',
                      consumer_secret='hA67P0DOFE8jISpIMgqp25rAxh2WpEhtrlyEQw6diluaJwdGkm',
                      access_token_key='23463646-j5rbrfFGlMPmQMK7dsL1IC6f5g8K5GuccwKykU8PK',
                      access_token_secret='VOsJmHgp7o8gkMxlB5ffMRjeTTD3wIAx2MO2CYLA37O2r')

    twitter_user = "spand_ex"
    statuses = api.GetUserTimeline(screen_name=twitter_user)

    twitter_statuses = []

    for s in statuses:
        status = {}
        status["text"] = s.text
        status["status_id"] = s.id

        if s.media != []:
            status["media"] = []
            for media in s.media:
                media_item = {}
                media_item["display_url"] = media["display_url"]
                media_item["media_url"] = media["media_url"]
                media_item["type"] = media["type"]
                status["media"].append(media_item)


        status["created_date"] = s.created_at
        
        usr = s.user
        status["user_id"] = usr.id
        status["user_name"] = usr.name 
        status["profile_background_color"] = usr.profile_background_color
        status["profile_background_image_url"] = usr.profile_background_image_url
        status["profile_image_url"] = usr.profile_image_url
        status["profile_link_color"] = usr.profile_link_color
        status["user_url"] = usr.url
        status["profile_sidebar_fill_color"] = usr.profile_sidebar_fill_color
        status["user_screen_name"] = usr.screen_name

        twitter_statuses.append(status)

    return render_template('home.html', nav=nav_init(), tweets=twitter_statuses)

def unicode_csv_reader(utf8_data, **kwargs):
    csv_reader = csv.reader(utf8_data, **kwargs)
    for row in csv_reader:
        yield [unicode(cell, 'utf-8') for cell in row]

@spandex.route('/dave-cite')
def dave():
    
    filename = 'citations.csv'
    reader = unicode_csv_reader(open(filename))
    allCitations = []
    
    for i, row in enumerate(reader):
        if i != 0:
            allCitations.append({"authors": row[0], "title": row[1], "publication": row[2], "volume" : row[3], "number" : row[4], "pages" : row[5], "year": row[6], "publisher": row[7]})

    for citation in allCitations:
        string = citation["authors"][:-2] + ".(" + citation["year"] + "). " + citation["title"] + ". " + citation["publication"]
        if citation["volume"] != '':
            string += ", " + citation["volume"]
        if citation["number"] != '':
            string += "(" + citation["number"] + ") "
        if citation["pages"] != '':
            string += ", " + citation["pages"]

        string += '.'

        
        
        publication = Publication()
        publication.other_researchers= citation["authors"].encode('ascii', 'ignore')
        publication.full_title = citation["title"].encode('ascii', 'ignore')
        publication.citation= string.encode('ascii', 'ignore')
        publication.researchers = [User.query.get(6)]

        db.session.add(publication)


    db.session.commit()

    return "Hi"

# Researchers
@spandex.route('/researchers/')
def researcherpage():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.name.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    users = User.query.order_by(User.name.asc()).all()
    return render_template('researchers.html', nav=nav_init(), researchers=users)

@spandex.route('/researchers/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()

    posts = user.projects.order_by(Project.timestamp.desc())

    if user.publications:
        publications = user.publications.filter_by(active=True).order_by(Publication.year_published.desc())[:5]


    return render_template('user.html', nav=nav_init(), user=user, posts=posts, publications=publications)

@spandex.route('/researchers/<user>/projects')
def user_projects(user):
    user = User.query.filter_by(username=user).first() 
    if user is None:
        abort(404)

    page = request.args.get('page', 1, type=int)

    pagination = Project.query.filter(Project.researchers.any(id=user.id)).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items

    ptype = "Project"

    return render_template('projects.html', user=user, posts=posts, ptype=ptype, nav=nav_init())


# Profile Editing
@spandex.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        tweet = re.sub('[@]', '', form.twitter.data)

        current_user.name = form.name.data
        current_user.jobtitle = form.jobtitle.data 
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        current_user.quals = form.quals.data
        current_user.pub_email = form.pub_email.data
        current_user.website = form.website.data
        current_user.twitter = form.twitter.data
        current_user.twitter_name = tweet
        current_user.linkedin = form.linkedin.data
        current_user.google = form.google.data
        current_user.google_scholar = form.google_scholar.data
        current_user.research_gate = form.research_gate.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.jobtitle.data = current_user.jobtitle
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    form.quals.data = current_user.quals
    form.pub_email.data = current_user.pub_email
    form.website.data = current_user.website
    form.twitter.data = current_user.twitter
    form.linkedin.data = current_user.linkedin
    form.google.data = current_user.google
    form.google_scholar.data = current_user.google_scholar
    form.research_gate.data = current_user.research_gate

    ptype = "Profile"
    user = current_user.name
    return render_template('edit_something.html', user=user, form=form, ptype=ptype, nav=nav_init())


@spandex.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        tweet = re.sub('[@]', '', form.twitter.data)

        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.jobtitle = form.jobtitle.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        user.quals = form.quals.data
        user.pub_email = form.pub_email.data
        user.website = form.website.data
        user.twitter = form.twitter.data
        user.twitter_name = tweet
        user.linkedin = form.linkedin.data
        user.google = form.google.data
        user.google_scholar = form.google_scholar.data
        user.research_gate = form.research_gate.data
        user.tw_confirmed = form.tw_confirmed.data
        user.tw_widget_id = form.tw_widget_id.data
        db.session.add(user)
        flash('The profile has been updated.')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.jobtitle.data = user.jobtitle
    form.location.data = user.location
    form.about_me.data = user.about_me
    form.quals.data = user.quals
    form.pub_email.data = user.pub_email
    form.website.data = user.website
    form.twitter.data = user.twitter
    form.linkedin.data = user.linkedin
    form.google.data = user.google
    form.google_scholar.data = user.google_scholar
    form.research_gate.data = user.research_gate
    form.tw_confirmed.data = user.tw_confirmed
    form.tw_widget_id.data = user.tw_widget_id

    ptype = "Profile"
    return render_template('edit_something.html', form=form, user=user, ptype=ptype, nav=nav_init())

# Projects

app/spandex/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post projects col-md-12">
        <script>var active = '{{ post.active }}';
                console.log(active)</script>
        <div class="post-content" style="{% if post.active != True %}background: #ecf0f1;{% endif %}">
            {% if post.active != True %}
                <span class="badge">Not Public</span>
            {% endif %}
            <h3>{{post.title}}</h3>
            <h5><a href="{{ url_for('.projnamepage', id=post.id) }}">{{post.full_title}}</a></h5>
            {% if post.website %}<b>Website: </b><a href="{{ url_for('.projnamepage', id=post.id) }}" target="_blank">{{post.website}}</a>{% endif %}<br/>
            <div class="post-author"><b>Researchers</b>: {% for researcher in post.researchers %}
                <img class="img-circle" src="{{ researcher.gravatar(size=20) }}"> <a href="{{ url_for('.user', username=researcher.username) }}">{{ researcher.name }}</a>{% endfor %}</div>
                 {% if post.other_researchers %}
                <b>External Researchers: </b> {{ post.other_researchers }}
                {% endif %}
                {% if post.publications.count() >= 1 %}
                <b>Associated Publications:</b> <ul>
                    {% for publication in post.publications %}
                        <li><a href="{{ url_for('.pubnamepage', id=publication.id) }}">{{ publication.full_title }}</a></li>
                    {% endfor %}
                </ul>
                
                {% endif %}

            </p>
            {% if post.brief_synopsis %}
            <p class="post-body">{{ post.brief_synopsis }}</p>
            {% endif %}
            <p class="post-body">{% if post.twitter_name %}
                <a href = "http://twitter.com/{{ post.twitter_name }}" target="_blank"><span class="socicon">a</span> {{ post.twitter_name }}</a>&nbsp;
            {% endif %}
            {% if post.facebook %}
                <a href = "{{ post.facebook }}"><span class="socicon">b</span></a> &nbsp;
            {% endif %}
           </p>
           <a class="btn btn-default" href="{{ url_for('.projnamepage', id=post.id) }}"><span class="glyphicon glyphicon-eye-open"></span> View</a>
           {% for researcher in post.researchers %}
                {% if current_user == researcher  %}
                <a class="btn btn-primary" href="{{ url_for('.edit_project', id=post.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
                 {% endif %}
                {% endfor %}
            {% if current_user.is_administrator() %}
            <a class="btn btn-danger" href="{{ url_for('.edit_project', id=post.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit [Admin]</a>
            {% endif %}
           
            </div>
             </p>
        </li>
        {% endfor %}
</ul>

app/spandex/templates/_publications.html
<ul class="posts">
    {% for publication in publications %}
    <li class="post">
        <div class="post-content" style="{% if publication.active != True %}background: #ecf0f1;{% endif %}">
            {% if publication.active != True %}
                <span class="badge">Not Public</span>
            {% endif %}
            <h5><a href="{{ url_for('.pubnamepage', id=publication.id) }}">{{publication.full_title}}</h5></a>
            <div class="post-author"><b>Researchers</b>: <span class="researcher_list">{% for researcher in publication.researchers %}
                        <img class="img-circle" src="{{ researcher.gravatar(size=20) }}"> <a href="{{ url_for('.user', username=researcher.username) }}" ><a href="{{ url_for('.user', username=researcher.username) }}" class="sublink">{{ researcher.name }}</a></span>{% endfor %}<br/>
                {% if publication.other_researchers %}
                <b>Author List: </b> {{ publication.other_researchers }} <br/>
                {% endif %}
                {% if publication.projects %}
                        <b>Project</b>: <a href="{{ url_for('.projnamepage', id=publication.id) }}" class="sublink"><span class="text-capitalize">{{ publication.projects.title }}</span></a></div>
                {% endif %}
            <div class="post-author">
                <p><b>Citation</b>: {{publication.citation}}</p>
                {% if publication.brief_synopsis %}
                <p> {{ publication.brief_synopsis }}</p>
                {% endif %}
            <p class="post-body">

            <a class="btn btn-default" href="{{ url_for('.pubnamepage', id=publication.id) }}"><span class="glyphicon glyphicon-eye-open"></span> View</a>
            {% for researcher in publication.researchers %}
                {% if current_user == researcher  %}
                <a class="btn btn-primary" href="{{ url_for('.edit_publication', id=publication.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
                {% endif %}
                {% endfor %}
            {% if current_user.is_administrator() %}
            <a class="btn btn-danger" href="{{ url_for('.edit_publication', id=publication.id) }}"><span class="glyphicon glyphicon-pencil"></span> Edit [Admin]</a>
            {% endif %}

        </p>
        </div>
        </li>
        {% endfor %}
</ul>

app/spandex/templates/_researchers.html
<ul class="posts">
    {% for researcher in researchers %}
    <li class="post researchers col-md-3">
        <div class="post-content">
            <img class="img-circle center-block" src="{{ researcher.gravatar(size=100) }}">
             <h3><a href="{{ url_for('.user', username=researcher.username) }}">{{ researcher.name }}</a></h3>
        {% if researcher.jobtitle %}
        <h5>{{ researcher.jobtitle }}</h5>
        {% endif %}
        {% if researcher.pub_email or researcher.twitter or researcher.linkedin or researcher.google %}
            {% if researcher.pub_email %}
                <a href = "mailto: {{researcher.pub_email}}"><span class="socicon">1</span></a> &nbsp;
                {% else %}
                <a href = "mailto: {{researcher.email}}"><span class="socicon">1</span></a> &nbsp;
            {% endif %}
            {% if researcher.twitter_name %}
                <a href = "http://twitter.com/{{ researcher.twitter_name }}" target="_blank"><span class="socicon">a</span></a> &nbsp;
            {% endif %}
            {% if researcher.linkedin %}
                <a href = "{{ researcher.linkedin }}"><span class="socicon">j</span></a> &nbsp;
            {% endif %}
            {% if researcher.google %}
                <a href = "{{ researcher.google }}"><span class="socicon">c</span></a> &nbsp;
            {% endif %}

        {% endif %}
        {% if current_user.is_administrator() %}
        <p><a class= "badge" href="mailto:{{ researcher.email }}">{{ researcher.email }}</a><br>
        <span class="badge">Last seen {{ moment(researcher.last_seen).fromNow() }}.</span>
        {% endif %}
           
           
            </div>
             </p>
        </li>
        {% endfor %}
</ul>

app/spandex/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}SPANDEX{% endblock %}

{% block head %}

{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link href="https://fontastic.s3.amazonaws.com/52jGWAx5sbFN9k6xZt7EAZ/icons.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='jquery.datetimepicker.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('spandex.index') }}">SP<span class="lc-icon-delta"></span>NDEX</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('spandex.landing') }}">Landing</a></li>
                <li><a href="{{ url_for('spandex.user', username=current_user.username) }}">Profile</a></li>               
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Researchers <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('spandex.researcherpage') }}">All</a></li>
                        {% for researcher in nav.researchers %}
                        <li><a href="{{ url_for('spandex.user', username=researcher.username) }}">{{ researcher.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Projects <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                         <li><a href="{{ url_for('spandex.projectpage') }}">All</a></li>
                         {% for project in nav.projects %}
                         <li><a href="{{ url_for('spandex.projnamepage', id=project.id) }}">{{ project.title }}</a></li>
                         {% endfor %}
                        {% if current_user.is_authenticated() %}                       
                        <li role="presentation" class="divider"></li>
                        <li class="add"><a href="{{ url_for('spandex.postproject') }}"><span class="glyphicon glyphicon-plus"></span>  Post a Project</a></li>
                        {% endif %}
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Publications <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('spandex.publicationpage') }}">All</a></li>
                        {% for project in nav.projects %}
                        <li><a href="{{ url_for('spandex.projectpublications', id=project.id) }}">{{ project.title }}</a></li>
                        {% endfor %}
                        {% if current_user.is_authenticated() %}
                        
                        <li class="add"><a href="{{ url_for('spandex.postpublication') }}"><span class="glyphicon glyphicon-plus"></span>  Post a Publication</a></li>
                        {% endif %}
                    </ul>
                </li>
                
               
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://lifecycle.ex.ac.uk/blog"></span>&nbsp; Blog</a></li>
                {% if current_user.is_authenticated() %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}"><span class="glyphicon glyphicon-tree-conifer"></span>&nbsp; Member Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script src="{{ url_for('static', filename='jquery.datetimepicker.min.js') }}"></script>
<script>
$.datetimepicker.setLocale('en');
$('#week').datetimepicker({
    format:'Y-m-d H:i:s'
});
</script>
<script>
$( document ).ready(function() {

    var checktype = '{{ptype}}'
    var type;

    if (checktype = 'Project') {
        type = 'projects'
    } else if (checktype = 'Publication') {
        type = 'publications'
    } else {
        type = '';
    }

    
    $.ajax({
        url: '{{ url_for("spandex.researchersjson") }}'
        }).done(function (data) {

            var names = data.json_list

                $.each(names, function(key, val){
                    $("#researchers").attr("disabled", false)
                    $("#researchers").after('<div class="authortag">' + val + '</div>')                
                });

            $('.authortag').click(function(){
                var txt = $(this).text()
                console.log(txt)
                $('#researchers').val(function(i,val) { 
                     return val + (!val ? '' : ', ') + txt;
                });
            });
        });

    $.ajax({
        url: '{{ url_for("spandex.projectsjson") }}'
        }).done(function (data) {
            
            var names = data.json_list
                $.each(names, function(key, val){
                    $("#project_name").attr("disabled", false)
                    $("#project_name").after('<div class="pubtag">' + val + '</div>')                
                });

            $('.pubtag').click(function(){
                var txt = $(this).text()
                console.log(txt)
                $('#project_name').val(txt);
            });
        });

    $("label[for='synopsis']").after('<br><small>HTML tags allowed: &lt;b&gt;<b>bold</b>&lt;/b&gt; &lt;abbr&gt;abbreviation&lt;/abbr&gt; &lt;acronym&gt;acronym&lt;/acronym&gt; &lt;a href="URL"&gt;<a href="http://google.com" target="none">link</a>&lt;/a&gt; &lt;em&gt;<em>italics</em>&lt;/em&gt; &lt;code&gt;<code>code block</code>&lt;/code&gt; &lt;ol&gt; ordered (numbered) list &lt;/ol&gt; &lt;pre&gt;preformatted text&lt;/pre&gt; &lt;ul&gt;unordered list&lt;/ul&gt; &lt;li&gt;list item&lt;/li&gt; &lt;p&gt;paragraph block&lt;/p&gt; &lt;h3&gt;heading&lt;/h3&gt; &lt;br/&gt; line break<br><a href="http://www.w3schools.com/tags/default.asp" target="new">Full spec here</a></small>');
});

document.getElementById("flask-pagedown-synopsis").rows = "30";

</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
{{ moment.include_moment() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/spandex/templates/edit_page.html
{% extends "demography_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Demography - Add Page{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit {{page.title}}</h1>
</div>
<div class="col-md-12 wtform">
    {{ wtf.quick_form(form) }}
</div>


{% endblock %}

app/spandex/templates/edit_project.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Post{% endblock %}

{% block page_content %}

<div class="page-header"> 
	<h1>Edit Post</h1>
</div> 

<div>
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}

{% endblock %}

app/spandex/templates/home.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}SPANDEX{% endblock %}

{% block page_content %}
<div class="banner jumbotron welcome">

		<h1>SP<span class="lc-icon-delta"></span>NDEX</h1>
		<hr/>
		<span>The Home of Demographic Research</span>
		<hr/>
		<p align="justify">SPANDEX (Statistical, Population, Applied, Natural and Demographic Ecology at eXeter) is a research group dedicated to the improved understanding of ecological dynamics. We research fundamental and applied ecological questions, create and test theory, develop and apply mathematical and statistical tools, and celebrate biodiversity in all its forms. Here you will find links to group members and our wider collaborative network; links to our current and past research projects; links to our publications and grants; and links to social media and the impact of our research. Associated pages link to biodiversity databases and outreach materials that we host or mirror. We operate under the broader banner of <a href="http://lifecycle.ex.ac.uk">“Life Cycle”</a>, to reflect the themes of demography and life history evolution in all of our research. Welcome, and we hope you enjoy and benefit from your visit.</p>
</div>

<h3>Recent Updates</h3>
<div id="tweets" class="row-fluid">
{% for tweet in tweets[-6:] %}
	<div class="tweetweet col-xs-12 col-lg-5 col-md-3" style="padding: 10px 5px 5px 10px; margin: 10px 5px 5px 10px; background: #ecf0f1">
		<div class="row">
			<div class="{% if tweet.media %}col-xs-6{% else %}col-xs-12{% endif %}">
				<p>"{{ tweet.text }}"</p>
				by <img src="{{ tweet.profile_image_url }}" class="img-circle" width="20">&nbsp;<a href="http://twitter.com/{{tweet.user_screen_name}}" target="none" style="color: #{{ tweet.profile_link_color }}">@{{ tweet.user_screen_name }}</a>
			</div>
				{% if tweet.media %}
				<div class="col-xs-5">
					
					{% for media in tweet.media[-1:] %}
					
						<img src="{{ media.media_url }}" class="img-responsive"><br/>
					
					{% endfor %}
			    </div>	
				{% endif %}

		</div>
		
	</div>
{% endfor %}
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{{ url_for('static', filename='impress.js') }}"></script>
<script>impress().init();
</script>
{% endblock %}

app/spandex/templates/project_publication.html
{% extends "base.html" %}

{% block page_content %}

<h2>{{ project.title }} Publications</h2>
{% if current_user.is_authenticated() %}
	<a class="btn btn-default" href="{{ url_for('spandex.postpublication') }}"><span class="glyphicon glyphicon-plus"></span> Add a new Publication</a>
{% endif %}

{% if publications|length == 0 %}
	<ul class="posts">
		<li class="post" >
        	<div class="post-content" align="center"> No publications yet </div>
    	</li>
    </ul>
{% else %}
{% include '_publications.html' %}
{% endif %}

{% endblock %}

app/spandex/templates/projects.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_content %}

<h2>All Projects</h2>
{% if current_user.is_authenticated() %}
<a class="btn btn-default" href="{{ url_for('spandex.postproject') }}"><span class="glyphicon glyphicon-plus"></span> Add a new Project</a>
{% endif %}

{% include '_posts.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}

{% endblock %}

app/spandex/templates/publications.html
{% extends "base.html" %}

{% block page_content %}

<h2>{{ title }}</h2>
{% if current_user.is_authenticated() %}
	<a class="btn btn-default" href="{{ url_for('spandex.postpublication') }}"><span class="glyphicon glyphicon-plus"></span> Add a new Publication</a>
{% endif %}


{% include '_publications.html' %}

{% endblock %}

app/spandex/templates/researchers.html
{% extends "base.html" %}

{% block page_content %}

<h2>All Researchers</h2>


{% include '_researchers.html' %}

{% endblock %}